server:
  port: ${SERVER_PORT:8001}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: product-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/product}
    driver-class-name: org.postgresql.Driver
    username: thangavel
    password: password

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

auth-service:
  url: https://localhost:8001/api/v1/auth

security:
  jwt:
    secret-key: 2ac4f7c9174d32ae74e722aebaa7c45100dec243c7f80d103bf199d945d332f9
    expiration-time: 3600000

logging:
  level:
    feign:
      client: DEBUG
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
        cloud:
          openfeign: DEBUG

